pages = [{"l":"index.html#","e":false,"i":"","n":"verifierLab6","t":"verifierLab6","d":"","k":"static","x":""},
{"l":"u06.html#","e":false,"i":"","n":"u06","t":"u06","d":"","k":"package","x":""},
{"l":"u06/examples.html#","e":false,"i":"","n":"u06.examples","t":"u06.examples","d":"","k":"package","x":""},
{"l":"u06/examples/ReadersAndWriters$.html#","e":false,"i":"","n":"ReadersAndWriters","t":"ReadersAndWriters extends App","d":"u06.examples","k":"object","x":""},
{"l":"u06/modelling.html#","e":false,"i":"","n":"u06.modelling","t":"u06.modelling","d":"","k":"package","x":""},
{"l":"u06/modelling/PetriNet$.html#","e":false,"i":"","n":"PetriNet","t":"PetriNet","d":"u06.modelling","k":"object","x":""},
{"l":"u06/modelling/PetriNet$.html#Marking-0","e":false,"i":"","n":"Marking","t":"Marking[P] = MSet[P]","d":"u06.modelling.PetriNet","k":"type","x":""},
{"l":"u06/modelling/PetriNet$.html#PetriNet-0","e":false,"i":"","n":"PetriNet","t":"PetriNet[P] = Set[Trn[P]]","d":"u06.modelling.PetriNet","k":"type","x":""},
{"l":"u06/modelling/PetriNet$.html#^^^-fffffeac","e":false,"i":"extension [P](self: Trn[P])","n":"^^^","t":"^^^(z: MSet[P]): Trn[P]","d":"u06.modelling.PetriNet","k":"def","x":""},
{"l":"u06/modelling/PetriNet$.html#apply-ffffffca","e":false,"i":"","n":"apply","t":"apply[P](transitions: Trn[P]*): PetriNet[P]","d":"u06.modelling.PetriNet","k":"def","x":""},
{"l":"u06/modelling/PetriNet$.html#toSystem-1f0","e":false,"i":"extension [P](pn: PetriNet[P])","n":"toSystem","t":"toSystem: System[MSet[P]]","d":"u06.modelling.PetriNet","k":"def","x":""},
{"l":"u06/modelling/PetriNet$.html#~~>-fffff842","e":false,"i":"extension [P](self: MSet[P])","n":"~~>","t":"~~>(y: MSet[P]): Trn[P]","d":"u06.modelling.PetriNet","k":"def","x":""},
{"l":"u06/modelling/PetriNet$$Trn.html#","e":false,"i":"","n":"Trn","t":"Trn[P](cond: MSet[P], eff: MSet[P], inh: MSet[P])","d":"u06.modelling.PetriNet","k":"class","x":""},
{"l":"u06/modelling/System.html#","e":false,"i":"","n":"System","t":"System[S]","d":"u06.modelling","k":"trait","x":""},
{"l":"u06/modelling/System.html#next-fffff081","e":false,"i":"","n":"next","t":"next(a: S): Set[S]","d":"u06.modelling.System","k":"def","x":""},
{"l":"u06/modelling/System$.html#","e":false,"i":"","n":"System","t":"System","d":"u06.modelling","k":"object","x":""},
{"l":"u06/modelling/System$.html#ofPartialFunction-4f1","e":false,"i":"","n":"ofPartialFunction","t":"ofPartialFunction[S](f: PartialFunction[S, Set[S]]): System[S]","d":"u06.modelling.System","k":"def","x":""},
{"l":"u06/modelling/System$.html#ofRelation-1f0","e":false,"i":"","n":"ofRelation","t":"ofRelation[S](rel: Set[(S, S)]): System[S]","d":"u06.modelling.System","k":"def","x":""},
{"l":"u06/modelling/System$.html#ofTransitions-16d","e":false,"i":"","n":"ofTransitions","t":"ofTransitions[S](rel: (S, S)*): System[S]","d":"u06.modelling.System","k":"def","x":""},
{"l":"u06/modelling/SystemAnalysis$.html#","e":false,"i":"","n":"SystemAnalysis","t":"SystemAnalysis","d":"u06.modelling","k":"object","x":""},
{"l":"u06/modelling/SystemAnalysis$.html#Path-0","e":false,"i":"","n":"Path","t":"Path[S] = List[S]","d":"u06.modelling.SystemAnalysis","k":"type","x":""},
{"l":"u06/modelling/SystemAnalysis$.html#complete-fffffbd0","e":false,"i":"extension [S](system: System[S])","n":"complete","t":"complete(p: List[S]): Boolean","d":"u06.modelling.SystemAnalysis","k":"def","x":""},
{"l":"u06/modelling/SystemAnalysis$.html#completePathsUpToDepth-15d","e":false,"i":"extension [S](system: System[S])","n":"completePathsUpToDepth","t":"completePathsUpToDepth(s: S, depth: Int): Seq[List[S]]","d":"u06.modelling.SystemAnalysis","k":"def","x":""},
{"l":"u06/modelling/SystemAnalysis$.html#normalForm-56b","e":false,"i":"extension [S](system: System[S])","n":"normalForm","t":"normalForm(s: S): Boolean","d":"u06.modelling.SystemAnalysis","k":"def","x":""},
{"l":"u06/modelling/SystemAnalysis$.html#paths-15d","e":false,"i":"extension [S](system: System[S])","n":"paths","t":"paths(s: S, depth: Int): Seq[List[S]]","d":"u06.modelling.SystemAnalysis","k":"def","x":""},
{"l":"u06/utils.html#","e":false,"i":"","n":"u06.utils","t":"u06.utils","d":"","k":"package","x":""},
{"l":"u06/utils/MSet.html#","e":false,"i":"","n":"MSet","t":"MSet[A] extends A => Int","d":"u06.utils","k":"trait","x":""},
{"l":"u06/utils/MSet.html#asList-0","e":false,"i":"","n":"asList","t":"asList: List[A]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet.html#asMap-0","e":false,"i":"","n":"asMap","t":"asMap: Map[A, Int]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet.html#diff-84a","e":false,"i":"","n":"diff","t":"diff(m: MSet[A]): MSet[A]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet.html#disjointed-4fb","e":false,"i":"","n":"disjointed","t":"disjointed(m: MSet[A]): Boolean","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet.html#extract-fffff942","e":false,"i":"","n":"extract","t":"extract(m: MSet[A]): Option[MSet[A]]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet.html#iterator-0","e":false,"i":"","n":"iterator","t":"iterator: Iterator[A]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet.html#map-ec5","e":false,"i":"","n":"map","t":"map[B](f: ((A, Int)) => (B, Int)): MSet[B]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet.html#matches-4fb","e":false,"i":"","n":"matches","t":"matches(m: MSet[A]): Boolean","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet.html#size-0","e":false,"i":"","n":"size","t":"size: Int","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet.html#union-84a","e":false,"i":"","n":"union","t":"union(m: MSet[A]): MSet[A]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet$.html#","e":false,"i":"","n":"MSet","t":"MSet","d":"u06.utils","k":"object","x":""},
{"l":"u06/utils/MSet$.html#*-fffffb34","e":false,"i":"extension (times: Int)","n":"*","t":"*[T](set: MSet[T]): MSet[T]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet$.html#+-440","e":false,"i":"extension [T](self: MSet[T])","n":"+","t":"+(other: MSet[T]): MSet[T]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet$.html#apply-21","e":false,"i":"","n":"apply","t":"apply[A](l: A*): MSet[A]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet$.html#ofList-fffff2c6","e":false,"i":"","n":"ofList","t":"ofList[A](l: List[A]): MSet[A]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/utils/MSet$.html#ofMap-a5e","e":false,"i":"","n":"ofMap","t":"ofMap[A](m: Map[A, Int]): MSet[A]","d":"u06.utils.MSet","k":"def","x":""},
{"l":"u06/verifier.html#","e":false,"i":"","n":"u06.verifier","t":"u06.verifier","d":"","k":"package","x":""},
{"l":"u06/verifier/util.html#","e":false,"i":"","n":"u06.verifier.util","t":"u06.verifier.util","d":"","k":"package","x":""},
{"l":"u06/verifier/util/PetriNets$.html#","e":false,"i":"","n":"PetriNets","t":"PetriNets","d":"u06.verifier.util","k":"object","x":""},
{"l":"u06/verifier/util/PetriNets$.html#PN-16d","e":false,"i":"","n":"PN","t":"PN[T](transitions: Trn[T]*): System[MSet[T]]","d":"u06.verifier.util.PetriNets","k":"def","x":""},
{"l":"u06/verifier/util/PetriNets$.html#\\-21","e":false,"i":"","n":"\\","t":"\\[A](l: A*): MSet[A]","d":"u06.verifier.util.PetriNets","k":"def","x":""},
{"l":"u06/verifier/util/PetriNets$.html#mutualExclusion-0","e":false,"i":"","n":"mutualExclusion","t":"mutualExclusion: System[MSet[Place3ME]]","d":"u06.verifier.util.PetriNets","k":"def","x":""},
{"l":"u06/verifier/util/PetriNets$.html#readersAndWriters-0","e":false,"i":"","n":"readersAndWriters","t":"readersAndWriters: System[MSet[Place7]]","d":"u06.verifier.util.PetriNets","k":"def","x":""},
{"l":"u06/verifier/util/PetriNets$$Place2.html#","e":false,"i":"","n":"Place2","t":"Place2","d":"u06.verifier.util.PetriNets","k":"enum","x":""},
{"l":"u06/verifier/util/PetriNets$$Place2.html#P1-0","e":false,"i":"","n":"P1","t":"P1 extends Place2","d":"u06.verifier.util.PetriNets.Place2","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place2.html#P2-0","e":false,"i":"","n":"P2","t":"P2 extends Place2","d":"u06.verifier.util.PetriNets.Place2","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place3.html#","e":false,"i":"","n":"Place3","t":"Place3","d":"u06.verifier.util.PetriNets","k":"enum","x":""},
{"l":"u06/verifier/util/PetriNets$$Place3.html#P1-0","e":false,"i":"","n":"P1","t":"P1 extends Place3","d":"u06.verifier.util.PetriNets.Place3","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place3.html#P2-0","e":false,"i":"","n":"P2","t":"P2 extends Place3","d":"u06.verifier.util.PetriNets.Place3","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place3.html#P3-0","e":false,"i":"","n":"P3","t":"P3 extends Place3","d":"u06.verifier.util.PetriNets.Place3","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place3ME.html#","e":false,"i":"","n":"Place3ME","t":"Place3ME","d":"u06.verifier.util.PetriNets","k":"enum","x":""},
{"l":"u06/verifier/util/PetriNets$$Place3ME.html#N-0","e":false,"i":"","n":"N","t":"N extends Place3ME","d":"u06.verifier.util.PetriNets.Place3ME","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place3ME.html#T-0","e":false,"i":"","n":"T","t":"T extends Place3ME","d":"u06.verifier.util.PetriNets.Place3ME","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place3ME.html#C-0","e":false,"i":"","n":"C","t":"C extends Place3ME","d":"u06.verifier.util.PetriNets.Place3ME","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place4.html#","e":false,"i":"","n":"Place4","t":"Place4","d":"u06.verifier.util.PetriNets","k":"enum","x":""},
{"l":"u06/verifier/util/PetriNets$$Place4.html#P1-0","e":false,"i":"","n":"P1","t":"P1 extends Place4","d":"u06.verifier.util.PetriNets.Place4","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place4.html#P2-0","e":false,"i":"","n":"P2","t":"P2 extends Place4","d":"u06.verifier.util.PetriNets.Place4","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place4.html#P3-0","e":false,"i":"","n":"P3","t":"P3 extends Place4","d":"u06.verifier.util.PetriNets.Place4","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place4.html#P4-0","e":false,"i":"","n":"P4","t":"P4 extends Place4","d":"u06.verifier.util.PetriNets.Place4","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place5.html#","e":false,"i":"","n":"Place5","t":"Place5","d":"u06.verifier.util.PetriNets","k":"enum","x":""},
{"l":"u06/verifier/util/PetriNets$$Place5.html#P1-0","e":false,"i":"","n":"P1","t":"P1 extends Place5","d":"u06.verifier.util.PetriNets.Place5","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place5.html#P2-0","e":false,"i":"","n":"P2","t":"P2 extends Place5","d":"u06.verifier.util.PetriNets.Place5","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place5.html#P3-0","e":false,"i":"","n":"P3","t":"P3 extends Place5","d":"u06.verifier.util.PetriNets.Place5","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place5.html#P4-0","e":false,"i":"","n":"P4","t":"P4 extends Place5","d":"u06.verifier.util.PetriNets.Place5","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place5.html#P5-0","e":false,"i":"","n":"P5","t":"P5 extends Place5","d":"u06.verifier.util.PetriNets.Place5","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place6.html#","e":false,"i":"","n":"Place6","t":"Place6","d":"u06.verifier.util.PetriNets","k":"enum","x":""},
{"l":"u06/verifier/util/PetriNets$$Place6.html#P1-0","e":false,"i":"","n":"P1","t":"P1 extends Place6","d":"u06.verifier.util.PetriNets.Place6","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place6.html#P2-0","e":false,"i":"","n":"P2","t":"P2 extends Place6","d":"u06.verifier.util.PetriNets.Place6","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place6.html#P3-0","e":false,"i":"","n":"P3","t":"P3 extends Place6","d":"u06.verifier.util.PetriNets.Place6","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place6.html#P4-0","e":false,"i":"","n":"P4","t":"P4 extends Place6","d":"u06.verifier.util.PetriNets.Place6","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place6.html#P5-0","e":false,"i":"","n":"P5","t":"P5 extends Place6","d":"u06.verifier.util.PetriNets.Place6","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place6.html#P6-0","e":false,"i":"","n":"P6","t":"P6 extends Place6","d":"u06.verifier.util.PetriNets.Place6","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place7.html#","e":false,"i":"","n":"Place7","t":"Place7","d":"u06.verifier.util.PetriNets","k":"enum","x":""},
{"l":"u06/verifier/util/PetriNets$$Place7.html#P1-0","e":false,"i":"","n":"P1","t":"P1 extends Place7","d":"u06.verifier.util.PetriNets.Place7","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place7.html#P2-0","e":false,"i":"","n":"P2","t":"P2 extends Place7","d":"u06.verifier.util.PetriNets.Place7","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place7.html#P3-0","e":false,"i":"","n":"P3","t":"P3 extends Place7","d":"u06.verifier.util.PetriNets.Place7","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place7.html#P4-0","e":false,"i":"","n":"P4","t":"P4 extends Place7","d":"u06.verifier.util.PetriNets.Place7","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place7.html#P5-0","e":false,"i":"","n":"P5","t":"P5 extends Place7","d":"u06.verifier.util.PetriNets.Place7","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place7.html#P6-0","e":false,"i":"","n":"P6","t":"P6 extends Place7","d":"u06.verifier.util.PetriNets.Place7","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$Place7.html#P7-0","e":false,"i":"","n":"P7","t":"P7 extends Place7","d":"u06.verifier.util.PetriNets.Place7","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceBrusselator.html#","e":false,"i":"","n":"PlaceBrusselator","t":"PlaceBrusselator","d":"u06.verifier.util.PetriNets","k":"enum","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceBrusselator.html#A-0","e":false,"i":"","n":"A","t":"A extends PlaceBrusselator","d":"u06.verifier.util.PetriNets.PlaceBrusselator","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceBrusselator.html#B-0","e":false,"i":"","n":"B","t":"B extends PlaceBrusselator","d":"u06.verifier.util.PetriNets.PlaceBrusselator","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceBrusselator.html#X-0","e":false,"i":"","n":"X","t":"X extends PlaceBrusselator","d":"u06.verifier.util.PetriNets.PlaceBrusselator","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceBrusselator.html#Y-0","e":false,"i":"","n":"Y","t":"Y extends PlaceBrusselator","d":"u06.verifier.util.PetriNets.PlaceBrusselator","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceBrusselator.html#D-0","e":false,"i":"","n":"D","t":"D extends PlaceBrusselator","d":"u06.verifier.util.PetriNets.PlaceBrusselator","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceBrusselator.html#E-0","e":false,"i":"","n":"E","t":"E extends PlaceBrusselator","d":"u06.verifier.util.PetriNets.PlaceBrusselator","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceRW.html#","e":false,"i":"","n":"PlaceRW","t":"PlaceRW","d":"u06.verifier.util.PetriNets","k":"enum","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceRW.html#P1-0","e":false,"i":"","n":"P1","t":"P1 extends PlaceRW","d":"u06.verifier.util.PetriNets.PlaceRW","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceRW.html#P2-0","e":false,"i":"","n":"P2","t":"P2 extends PlaceRW","d":"u06.verifier.util.PetriNets.PlaceRW","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceRW.html#P3-0","e":false,"i":"","n":"P3","t":"P3 extends PlaceRW","d":"u06.verifier.util.PetriNets.PlaceRW","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceRW.html#P4-0","e":false,"i":"","n":"P4","t":"P4 extends PlaceRW","d":"u06.verifier.util.PetriNets.PlaceRW","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceRW.html#Lock-0","e":false,"i":"","n":"Lock","t":"Lock extends PlaceRW","d":"u06.verifier.util.PetriNets.PlaceRW","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceRW.html#Reading-0","e":false,"i":"","n":"Reading","t":"Reading extends PlaceRW","d":"u06.verifier.util.PetriNets.PlaceRW","k":"case","x":""},
{"l":"u06/verifier/util/PetriNets$$PlaceRW.html#Writing-0","e":false,"i":"","n":"Writing","t":"Writing extends PlaceRW","d":"u06.verifier.util.PetriNets.PlaceRW","k":"case","x":""},
{"l":"u06/verifier/Checking$.html#","e":false,"i":"","n":"Checking","t":"Checking","d":"u06.verifier","k":"object","x":""},
{"l":"u06/verifier/Checking$.html#E-fffffbdd","e":false,"i":"","n":"E","t":"E[T, C](searchSpace: (System[T]) => Iterable[C])(condition: C => Boolean)(using s: System[T]): Boolean","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#Limit-0","e":false,"i":"","n":"Limit","t":"Limit = Int","d":"u06.verifier.Checking","k":"type","x":""},
{"l":"u06/verifier/Checking$.html#Paths-0","e":false,"i":"","n":"Paths","t":"Paths[T] = Seq[List[T]]","d":"u06.verifier.Checking","k":"type","x":""},
{"l":"u06/verifier/Checking$.html#ReachedDef-0","e":false,"i":"","n":"ReachedDef","t":"ReachedDef[T] = T => T => Boolean","d":"u06.verifier.Checking","k":"type","x":""},
{"l":"u06/verifier/Checking$.html#bounded-d39","e":false,"i":"","n":"bounded","t":"bounded[T](using s: System[MSet[T]])(startPoint: MSet[T]): Boolean","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#from-fffff49f","e":false,"i":"extension [T, Result](x: T => (System[T]) => Result)","n":"from","t":"from(p: T): (System[T]) => Result","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#from-fffffb45","e":false,"i":"extension [T, Result](x: T => Result)","n":"from","t":"from(p: T): Result","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#hasMarkingThat-fffff0f0","e":false,"i":"extension [T](x: List[T])","n":"hasMarkingThat","t":"hasMarkingThat(condition: T => Boolean): Boolean","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#livenessL1-93b","e":false,"i":"","n":"livenessL1","t":"livenessL1[T](transition: Trn[T])(startPoint: MSet[T])(using s: System[MSet[T]])(using Limit): Boolean","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#markingMatchedDefinition-c40","e":false,"i":"","n":"markingMatchedDefinition","t":"markingMatchedDefinition[T]: () => MSet[T]","d":"u06.verifier.Checking","k":"given","x":""},
{"l":"u06/verifier/Checking$.html#markingReachedDefinition-c40","e":false,"i":"","n":"markingReachedDefinition","t":"markingReachedDefinition[T]: () => MSet[T]","d":"u06.verifier.Checking","k":"given","x":""},
{"l":"u06/verifier/Checking$.html#next-15c","e":false,"i":"","n":"next","t":"next[T](node: T)(using s: System[T]): (System[T]) => Set[T]","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#notE-fffffbdd","e":false,"i":"","n":"notE","t":"notE[T, C](searchSpace: (System[T]) => Iterable[C])(condition: C => Boolean)(using s: System[T]): Boolean","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#path-fbb","e":false,"i":"","n":"path","t":"path[T](using limit: Limit): T => (System[T]) => Paths[T]","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#reachable-fffffd6e","e":false,"i":"","n":"reachable","t":"reachable[T](destination: T)(startPoint: T)(using s: System[T])(using Limit)(using countAsHaveReached: () => T): Boolean","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#satisfies-fffff5f1","e":false,"i":"extension [T](x: System[T])","n":"satisfies","t":"satisfies(block: (System[T]) ?=> Boolean): Boolean","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#suchThat-fffff28f","e":false,"i":"extension [C](x: PartialFunction[C => Boolean, Boolean])","n":"suchThat","t":"suchThat(condition: C => Boolean): Boolean","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/Checking$.html#system-a53","e":false,"i":"","n":"system","t":"system[T](using s: System[T]): System[T]","d":"u06.verifier.Checking","k":"def","x":""},
{"l":"u06/verifier/PNChecking$.html#","e":false,"i":"","n":"PNChecking","t":"PNChecking","d":"u06.verifier","k":"object","x":""},
{"l":"u06/verifier/PNChecking$.html#hasTokens-fffff245","e":false,"i":"","n":"hasTokens","t":"hasTokens[T](markingWithTokens: MSet[T])(markingThatShouldContainTokens: MSet[T]): Boolean","d":"u06.verifier.PNChecking","k":"def","x":""}];