pages = [{"l":"index.html#","e":false,"i":"","n":"mvcEngineerLab4","t":"mvcEngineerLab4","d":"","k":"static","x":""},
{"l":"u04.html#","e":false,"i":"","n":"u04","t":"u04","d":"","k":"package","x":""},
{"l":"u04/monads.html#","e":false,"i":"","n":"u04.monads","t":"u04.monads","d":"","k":"package","x":""},
{"l":"u04/monads/Monads$.html#","e":false,"i":"","n":"Monads","t":"Monads","d":"u04.monads","k":"object","x":""},
{"l":"u04/monads/Monads$$Monad$.html#","e":false,"i":"","n":"Monad","t":"Monad","d":"u04.monads.Monads","k":"object","x":""},
{"l":"u04/monads/Monads$$Monad$.html#map2-fffff868","e":false,"i":"","n":"map2","t":"map2[M[_] : Monad, A, B, C](m: M[A], m2: => M[B])(f: (A, B) => C): M[C]","d":"u04.monads.Monads.Monad","k":"def","x":""},
{"l":"u04/monads/Monads$$Monad$.html#seq-5e9","e":false,"i":"","n":"seq","t":"seq[M[_] : Monad, A, B](m: M[A], m2: => M[B]): M[B]","d":"u04.monads.Monads.Monad","k":"def","x":""},
{"l":"u04/monads/Monads$$Monad$.html#seqN-fffffa53","e":false,"i":"","n":"seqN","t":"seqN[M[_] : Monad, A](stream: LazyList[M[A]]): M[A]","d":"u04.monads.Monads.Monad","k":"def","x":""},
{"l":"u04/monads/Monads$$Monad.html#","e":false,"i":"","n":"Monad","t":"Monad[M[_]]","d":"u04.monads.Monads","k":"trait","x":""},
{"l":"u04/monads/Monads$$Monad.html#flatMap-fffffd97","e":false,"i":"extension [A](m: M[A])","n":"flatMap","t":"flatMap[B](f: A => M[B]): M[B]","d":"u04.monads.Monads.Monad","k":"def","x":""},
{"l":"u04/monads/Monads$$Monad.html#map-fffffd97","e":false,"i":"extension [A](m: M[A])","n":"map","t":"map[B](f: A => B): M[B]","d":"u04.monads.Monads.Monad","k":"def","x":""},
{"l":"u04/monads/Monads$$Monad.html#unit-957","e":false,"i":"","n":"unit","t":"unit[A](a: A): M[A]","d":"u04.monads.Monads.Monad","k":"def","x":""},
{"l":"u04/monads/States$.html#","e":false,"i":"","n":"States","t":"States","d":"u04.monads","k":"object","x":""},
{"l":"u04/monads/States$.html#stateMonad-fffff64e","e":false,"i":"","n":"stateMonad","t":"stateMonad[S]: stateMonad[S]","d":"u04.monads.States","k":"given","x":""},
{"l":"u04/monads/States$$State.html#","e":false,"i":"","n":"State","t":"State[S, A](run: S => (S, A))","d":"u04.monads.States","k":"class","x":""},
{"l":"u04/monads/States$$State$.html#","e":false,"i":"","n":"State","t":"State","d":"u04.monads.States","k":"object","x":""},
{"l":"u04/monads/States$$State$.html#apply-887","e":false,"i":"extension [S, A](m: State[S, A])","n":"apply","t":"apply(s: S): (S, A)","d":"u04.monads.States.State","k":"def","x":""},
{"l":"u04/mvc/engineer.html#","e":false,"i":"","n":"u04.mvc.engineer","t":"u04.mvc.engineer","d":"","k":"package","x":""},
{"l":"u04/mvc/engineer.html#ballGame-94c","e":false,"i":"","n":"ballGame","t":"ballGame(): Unit","d":"u04.mvc.engineer","k":"def","x":""},
{"l":"u04/mvc/engineer/BallController$.html#","e":false,"i":"","n":"BallController","t":"BallController","d":"u04.mvc.engineer","k":"object","x":""},
{"l":"u04/mvc/engineer/BallController$$Controller.html#","e":false,"i":"","n":"Controller","t":"Controller","d":"u04.mvc.engineer.BallController","k":"trait","x":""},
{"l":"u04/mvc/engineer/BallController$$Controller.html#Event-0","e":false,"i":"","n":"Event","t":"Event","d":"u04.mvc.engineer.BallController.Controller","k":"type","x":""},
{"l":"u04/mvc/engineer/BallController$$Controller.html#Model-0","e":false,"i":"","n":"Model","t":"Model","d":"u04.mvc.engineer.BallController.Controller","k":"type","x":""},
{"l":"u04/mvc/engineer/BallController$$Controller.html#ModelOut-0","e":false,"i":"","n":"ModelOut","t":"ModelOut","d":"u04.mvc.engineer.BallController.Controller","k":"type","x":""},
{"l":"u04/mvc/engineer/BallController$$Controller.html#View-0","e":false,"i":"","n":"View","t":"View","d":"u04.mvc.engineer.BallController.Controller","k":"type","x":""},
{"l":"u04/mvc/engineer/BallController$$Controller.html#gameLoop-fffff779","e":false,"i":"","n":"gameLoop","t":"gameLoop(events: LazyList[Event], updateM: State[Model, ModelOut], updateV: ModelOut => State[View, Unit], period: FiniteDuration): State[(Model, View), Unit]","d":"u04.mvc.engineer.BallController.Controller","k":"def","x":""},
{"l":"u04/mvc/engineer/BallController$$ControllerImpl$.html#","e":false,"i":"","n":"ControllerImpl","t":"ControllerImpl extends Controller","d":"u04.mvc.engineer.BallController","k":"object","x":""},
{"l":"u04/mvc/engineer/BallController$$ControllerImpl$.html#Event-0","e":false,"i":"","n":"Event","t":"Event","d":"u04.mvc.engineer.BallController.ControllerImpl","k":"type","x":""},
{"l":"u04/mvc/engineer/BallController$$ControllerImpl$.html#Model-0","e":false,"i":"","n":"Model","t":"Model","d":"u04.mvc.engineer.BallController.ControllerImpl","k":"type","x":""},
{"l":"u04/mvc/engineer/BallController$$ControllerImpl$.html#ModelOut-0","e":false,"i":"","n":"ModelOut","t":"ModelOut","d":"u04.mvc.engineer.BallController.ControllerImpl","k":"type","x":""},
{"l":"u04/mvc/engineer/BallController$$ControllerImpl$.html#View-0","e":false,"i":"","n":"View","t":"View","d":"u04.mvc.engineer.BallController.ControllerImpl","k":"type","x":""},
{"l":"u04/mvc/engineer/BallController$$ControllerImpl$.html#mv-8dd","e":false,"i":"","n":"mv","t":"mv[SM, SV, AM, AV](m1: State[SM, AM], f: AM => State[SV, AV]): State[(SM, SV), AV]","d":"u04.mvc.engineer.BallController.ControllerImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallModel$.html#","e":false,"i":"","n":"BallModel","t":"BallModel","d":"u04.mvc.engineer","k":"object","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameState.html#","e":false,"i":"","n":"GameState","t":"GameState","d":"u04.mvc.engineer.BallModel","k":"trait","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameState.html#Ball-0","e":false,"i":"","n":"Ball","t":"Ball","d":"u04.mvc.engineer.BallModel.GameState","k":"type","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameState.html#BallPosition-0","e":false,"i":"","n":"BallPosition","t":"BallPosition = (Int, Int, Int)","d":"u04.mvc.engineer.BallModel.GameState","k":"type","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameState.html#Game-0","e":false,"i":"","n":"Game","t":"Game = (World, Ball)","d":"u04.mvc.engineer.BallModel.GameState","k":"type","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameState.html#World-0","e":false,"i":"","n":"World","t":"World","d":"u04.mvc.engineer.BallModel.GameState","k":"type","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameState.html#getBall-0","e":false,"i":"","n":"getBall","t":"getBall: State[Game, BallPosition]","d":"u04.mvc.engineer.BallModel.GameState","k":"def","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameState.html#nop-110","e":false,"i":"","n":"nop","t":"nop(): State[Game, Unit]","d":"u04.mvc.engineer.BallModel.GameState","k":"def","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameState.html#updateState-110","e":false,"i":"","n":"updateState","t":"updateState(): State[Game, Game]","d":"u04.mvc.engineer.BallModel.GameState","k":"def","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameStateImpl$.html#","e":false,"i":"","n":"GameStateImpl","t":"GameStateImpl extends GameState","d":"u04.mvc.engineer.BallModel","k":"object","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameStateImpl$.html#Ball-0","e":false,"i":"","n":"Ball","t":"Ball","d":"u04.mvc.engineer.BallModel.GameStateImpl","k":"type","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameStateImpl$.html#World-0","e":false,"i":"","n":"World","t":"World","d":"u04.mvc.engineer.BallModel.GameStateImpl","k":"type","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameStateImpl$.html#getBall-0","e":false,"i":"","n":"getBall","t":"getBall: State[Game, BallPosition]","d":"u04.mvc.engineer.BallModel.GameStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameStateImpl$.html#initialState-fffffef2","e":false,"i":"","n":"initialState","t":"initialState(width: Int, height: Int, speed: Int, ballRadius: Int): Game","d":"u04.mvc.engineer.BallModel.GameStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameStateImpl$.html#nop-110","e":false,"i":"","n":"nop","t":"nop(): State[Game, Unit]","d":"u04.mvc.engineer.BallModel.GameStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameStateImpl$.html#updateState-110","e":false,"i":"","n":"updateState","t":"updateState(): State[Game, Game]","d":"u04.mvc.engineer.BallModel.GameStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallModel$$GameStateImpl$$BallImpl.html#","e":false,"i":"","n":"BallImpl","t":"BallImpl(x: Int, y: Int, vx: Int, vy: Int, radius: Int)","d":"u04.mvc.engineer.BallModel.GameStateImpl","k":"class","x":""},
{"l":"u04/mvc/engineer/BallView$.html#","e":false,"i":"","n":"BallView","t":"BallView","d":"u04.mvc.engineer","k":"object","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowState.html#","e":false,"i":"","n":"WindowState","t":"WindowState","d":"u04.mvc.engineer.BallView","k":"trait","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowState.html#Window-0","e":false,"i":"","n":"Window","t":"Window","d":"u04.mvc.engineer.BallView.WindowState","k":"type","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowState.html#addBallView-110","e":false,"i":"","n":"addBallView","t":"addBallView(): State[Window, Unit]","d":"u04.mvc.engineer.BallView.WindowState","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowState.html#drawBall-b57","e":false,"i":"","n":"drawBall","t":"drawBall(x: Int, y: Int, radius: Int): State[Window, Unit]","d":"u04.mvc.engineer.BallView.WindowState","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowState.html#eventStream-110","e":false,"i":"","n":"eventStream","t":"eventStream(): State[Window, LazyList[String]]","d":"u04.mvc.engineer.BallView.WindowState","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowState.html#initialWindow-0","e":false,"i":"","n":"initialWindow","t":"initialWindow: Window","d":"u04.mvc.engineer.BallView.WindowState","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowState.html#setSize-fffffcf0","e":false,"i":"","n":"setSize","t":"setSize(width: Int, height: Int): State[Window, Unit]","d":"u04.mvc.engineer.BallView.WindowState","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowState.html#show-110","e":false,"i":"","n":"show","t":"show(): State[Window, Unit]","d":"u04.mvc.engineer.BallView.WindowState","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowStateImpl$.html#","e":false,"i":"","n":"WindowStateImpl","t":"WindowStateImpl extends WindowState","d":"u04.mvc.engineer.BallView","k":"object","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowStateImpl$.html#Window-0","e":false,"i":"","n":"Window","t":"Window = Frame","d":"u04.mvc.engineer.BallView.WindowStateImpl","k":"type","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowStateImpl$.html#addBallView-110","e":false,"i":"","n":"addBallView","t":"addBallView(): State[Window, Unit]","d":"u04.mvc.engineer.BallView.WindowStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowStateImpl$.html#drawBall-b57","e":false,"i":"","n":"drawBall","t":"drawBall(centerX: Int, centerY: Int, radius: Int): State[Window, Unit]","d":"u04.mvc.engineer.BallView.WindowStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowStateImpl$.html#eventStream-110","e":false,"i":"","n":"eventStream","t":"eventStream(): State[Window, LazyList[String]]","d":"u04.mvc.engineer.BallView.WindowStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowStateImpl$.html#initialWindow-0","e":false,"i":"","n":"initialWindow","t":"initialWindow: Window","d":"u04.mvc.engineer.BallView.WindowStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowStateImpl$.html#setSize-fffffcf0","e":false,"i":"","n":"setSize","t":"setSize(width: Int, height: Int): State[Window, Unit]","d":"u04.mvc.engineer.BallView.WindowStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/BallView$$WindowStateImpl$.html#show-110","e":false,"i":"","n":"show","t":"show(): State[Window, Unit]","d":"u04.mvc.engineer.BallView.WindowStateImpl","k":"def","x":""},
{"l":"u04/mvc/engineer/SwingCustomComponents$.html#","e":false,"i":"","n":"SwingCustomComponents","t":"SwingCustomComponents","d":"u04.mvc.engineer","k":"object","x":""},
{"l":"u04/mvc/engineer/SwingCustomComponents$$BallPanel.html#","e":false,"i":"","n":"BallPanel","t":"BallPanel extends JPanel","d":"u04.mvc.engineer.SwingCustomComponents","k":"class","x":""},
{"l":"u04/mvc/engineer/SwingCustomComponents$$BallPanel.html#drawBall-fffffbd3","e":false,"i":"","n":"drawBall","t":"drawBall(x: Int, y: Int, radius: Int): Unit","d":"u04.mvc.engineer.SwingCustomComponents.BallPanel","k":"def","x":""},
{"l":"u04/mvc/engineer/ballGame.html#","e":false,"i":"","n":"ballGame","t":"ballGame","d":"u04.mvc.engineer","k":"class","x":""}];